include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - dist/**
    - tools/**
    - .dart_tool/**
    - android/**/build/**
    - ios/**/build/**
    - windows/**/build/**

linter:
  rules:
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
